spring:
  kafka:
    bootstrap-servers: virtual.host:9092
    producer:
      retries: 2
      ##批量发送数据的配置
      batch-size: 16384
      #设置kafka 生产者内存缓存区的大小
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1
    consumer:
      enable-auto-commit: true
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
#      ack-mode: manual
      concurrency: 5