#server:
#  port: 8761
#eureka:
#  client:
#    # 是否要注册到其他Eureka Server实例
#    register-with-eureka: false
#    # 是否要从其他Eureka Server实例获取数据
#    fetch-registry: false
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#---
#Edit Configrations... 添加VM options -> -Dserver.port=8763,去掉single instance only的勾
spring:
  application:
    name: eureka-server-cluster
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/,http://peer1:8761/eureka/
