server:
  port: 8888
spring:
  application:
    name: config-server
  profiles:
    active: jdbc
  cloud:
    config:
      label: master
      server:
        jdbc:
          order: 0
          #key需要引号，否则mysql会报错。
          sql: SELECT 'KEY', VALUE from CONFIG_CENTER where APPLICATION=? and PROFILE=? and LABEL=?
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
#    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}


